# Use the base image for FrankenPHP
FROM dunglas/frankenphp:latest

# Set ENVIRONMENT as development
ENV ENVIRONMENT=development

# Install required PHP extensions for the application
RUN install-php-extensions \
    gd \
    opcache

# Optional: Set the FRANKENPHP_CONFIG environment variable to start FrankenPHP with a specific worker script
ENV FRANKENPHP_CONFIG="worker ./public/index.php"
