# Use a specific version of the PHP image for consistency and reliability
FROM dunglas/frankenphp:php8.3-alpine

# Set ENVIRONMENT as development
ENV ENVIRONMENT=development

# Set the working directory for the application
WORKDIR /app

# Copy the entire project directory to the container's working directory
COPY . /app

# Install required PHP extensions for the application
RUN install-php-extensions \
    gd \
    opcache

# Optional: Set the FRANKENPHP_CONFIG environment variable to start FrankenPHP with a specific worker script
ENV FRANKENPHP_CONFIG="worker ./public/index.php"
